AlexsLemonade/OpenPBTA-manuscript

README.md

Add manuscript description, refers to file created in [this PR](https://github.com/AlexsLemonade/OpenPBTA-manuscript/pull/22).

Add manuscript description

---

content/03.methods.md

Add DNA alignment header and removed germline CNV and SV headers

edit headers

---

content/03.methods.md

- Add CBTTC and PNOC biospecimen collection
- Add data generated and by whom
- Added information on library types/read lengths
- Mateusz will add nucleic acids extraction info (emailed TGEN about this for PNOC)

add biospecimen/data generation sections

---

content/03.methods.md

going into a separate germline paper

removing germline SV/CNV

---

content/03.methods.md

#45 
add panel details, remove cell line details not captured in any files

add panel methods

---

content/03.methods.md

Add description of independent sample selection.
https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/155

Description of independent sample selection

---

.github/ISSUE_TEMPLATE/propose-updates-to-manuscript.md

There is currently no template for manuscript issues. To be consistent with the OpenPBTA-analysis repo, adding a template here.
NA, or all, depending on how you look at it :P 
- [NA] All citations follow the [Manubot citation instructions](https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/USAGE.md#citations)
- [NA] All changes or additions to tables follow the [Manubot table instructions](https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/USAGE.md#tables)
- [NA] All figures follow the [Manubot figure instructions](https://github.com/jaclyn-taroni/OpenPBTA-manuscript/blob/master/USAGE.md#figur …

add issue template

---

content/03.methods.md

-Modify CNV methods
-Remove LUMPY methods
-Add stub for germline calls (since used in BAF calculations)
-Updated Medulloblastoma classifier link
-Clarify panel methods
#47 , #49 

Update 03.methods.md SNV/SV/classifier/panel

---

content/03.methods.md

- Add germline SNP calling methods as input to CNV algorithms for BAF calculations
#54 

add germline methods

---

content/03.methods.md

- Add Manta annotation, AnnotSV
- Update RSEM methods to clarify both TPM and FPKM were created from RSEM
#57 and [manta](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/272)

update RSEM; add annotSV

---

content/03.methods.md

Attempting to clarify some of the SNV methods:
- Added more info about WGS intervals in general
- Added WGS interval info to be inline with specific algorithms to avoid confusion
- Moved Lancet to end since it uses a different WGS interval input than the other 3 algorithms
[this issue](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/269) and #53 (this one still needs to be added)

update SNV methods

---

content/03.methods.md

-add MendQC methods
-update Lancet BED methods
-add GISTIC methods
-indicate when methods were run selectively
#72 #70 #69 #67 

add MendQC/GISTIC methods/modify Lancet methods/update selectivity

---

content/03.methods.md

BAF file generation is described, but missing in the alignment section was gvcf output used as input to create this.
Will still need to address references used for BAF step.
https://github.com/AlexsLemonade/OpenPBTA-manuscript/issues/73
- [x ] All changes to text follow "one sentence per line" [[Manubot instructions](https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/USAGE.md#manubot-markdown)]

Added some minor clarification of BAF file gen

---

content/03.methods.md

Adding TCGA SNV calling to [SNV and INDEL calling section](https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/content/03.methods.md#snv-and-indel-calling)
#71 
@jharenza 
Only changed the above section in methods document
Should we add how many samples were chosen under each disease type and list of all `primary_diagnosis` ? 
Yes

Adding TCGA SNV calling to methods

---

content/03.methods.md

This PR adds a description of the methods used to calculate scores for cooccurrence and recurrent mutations as used in the figure with that data.
Closes #95 
Is there sufficient detail to describe the method here? Is it clear?
I cited `maftools` as the calculation I performed is largely the same as theirs, but did not use their code at all. Do people think this citation is necessary?
Yes
However, if you want to update the first line to have an accurate count of words and you want to remove …

Add methods for cooccurrence

---

build/assets/custom-dictionary.txt
content/03.methods.md

In reviewing another pull request, I realized that we used both "polyA" and "poly-A" so I made that consistent. I also looked over the spelling list and saw two versions of "CNVkit" so I made those consistent as well.
None
Does it build?
Did I go the right direction with my choices?
Yup.  …

Fix inconsistencies in usage of poly-A and CNVkit

---

build/assets/custom-dictionary.txt
content/04.results.md

I'm adding a link to the CN-status heatmap final figure and some brief words describing what the figure represents and the current threshold of 75%.
I am unsure what big picture words to say about this figure at this point. 
- Mayhaps some of the words I added should be in a caption? 
- Are there details missing? 

Add figure link to CN status heatmap

---

build/assets/custom-dictionary.txt
content/03.methods.md
content/04.results.md

This pull requests adds the transcriptomic overview figure that contains UMAP, GSVA, and immune deconvolution panels. I'm also making the following changes:
* Adding a section on GSVA to the methods
* Adding a section on dimension reduction (restricted to UMAP for now - that's the only method currently included in the manuscript in some manner)
* I've significantly shortened some of the other sections in the gene expression sections, choosing instead to link out to the analysis module. There were some instances of information that were probably better suited to the results, but those figures have not made it into the manuscript yet.
Closes #96 
I would view these changes as an outline, rather than have a level of detail you might expect for publication. The lack of lettering on the figure …

Adds transcriptomic overview figure

---

build/assets/custom-dictionary.txt
content/04.results.md

Following the plan to get publication figures ready, I am adding the url to png for the oncoprint landscape figure found at `OpenPBTA-analysis/figures/pngs/fig3-oncoprint-landscape.png`
This is a part of issue [#571](https://github.com/AlexsLemonade/OpenPBTA-analysis/issues/571#issue-572964297) in the OpenPBTA-analysis repository.
- Are there any details that should be added?
- Is the current wording suffice?
**Note:** This figure is not yet complete as there is an open PR AlexsLemonade/OpenPBTA-analysis#711 which updates the oncoprint figure to include the genes with the top recurrent CNVs.
Yes. 
Edit the file in …

Add figure link to oncoprint by url

---

build/assets/custom-dictionary.txt
content/06.administrative.md
content/metadata.yaml

I need to add COI language in accordance with Penn's guidelines, so I also added myself as an author.
Does it build and render correctly?
We have some flexibility in the language if folks prefer something different.
Yes
```
(( len = …
```

add COI / admin items

---

content/metadata.yaml

Addresses Issue #114 to add @sjspielman as author in the metadata.yaml.

sjspielman authorshipt

---

content/metadata.yaml

Update author list and order to align better with CReDiT and contributions
- move Shrivats Kannan, Dan Miller, and Pichai Raman up for direct analysis contributions
- add `Supervision` to Hongbo Xie, and move later in author list
- change Angela Waanders' contribution to `Supervision` to align with her contributions
- Add Cassie Kline as author
#111 
na
no
yes
However, if you want to update the first line to …

update d3b authors and order

---

build/assets/custom-dictionary.txt
content/04.results.md
content/metadata.yaml

The purpose of this pull request is to add telomerase activity prediction subsection to the results section.
This pull request addresses Issue # 105: Results Telomerase Activity Prediction
Results section for telomerase activities
Results
NO
YES
- [ YES] All changes to text follow "one sentence per line" [[Manubot instructions](https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/USAGE.md#manubot-markdown)]
- [ YES] All citations follow the [Manubot citation instructions](https://github.com/AlexsLemonade/OpenPBTA-manuscript/blob/master/USAGE.md#citations)
- [ YES] All changes or additions to tables follow the …

TelomeraseResults_Section

---

content/metadata.yaml

- Add Xiaoyan Huang, Laura Scolaro, Yiran Guo
- Update Teja's email
#128 
NA
No
No
```
(( len = $(awk '!a[$0]++' < custom-dictionary.txt | wc -l ) - 1 )); tmpfile="$(mktemp)"; echo "personal_ws-1.1 en $len utf-8" > $tmpfile; tail -n +2 custom-dictionary.txt | awk '!a[$0]++' >> $tmpfile; …
```

add CHOP authors

---

build/assets/custom-dictionary.txt
content/03.methods.md

The following changes are included:
1) description of 'deep deletion' and `amplification` for focal-cn module 
2) description of changes in consensus calling 
3) description of TP53 `loss` and `activated` status calling.
https://github.com/AlexsLemonade/OpenPBTA-manuscript/issues/132
https://github.com/AlexsLemonade/OpenPBTA-manuscript/issues/133
https://github.com/AlexsLemonade/OpenPBTA-manuscript/issues/137
Please see whether the descriptions are clear and easy-to-read.
No
Yes
Edit the file in `build/assets/custom-dictionary.txt` by …

changes to copy_consensus focal_cn and tp53 status 

---

content/metadata.yaml

Update for current affiliations
Closes #142 
Does the build break?
```
(( len = $(awk '!a[$0]++' < custom-dictionary.txt | wc -l ) - 1 )); tmpfile="$(mktemp)"; echo "personal_ws-1.1 en $len utf-8" > $tmpfile; tail -n +2 custom-dictionary.txt | awk '!a[$0]++' >> $tmpfile; mv $tmpfile …
```

Add @cgreene current affiliations, closes #142

---

content/03.methods.md

Added a section under `molecular_subtype` to discuss subtyping of `EWS`.
https://github.com/AlexsLemonade/OpenPBTA-manuscript/issues/136
No.
No.
Yes.
```
(( len = $(awk '!a[$0]++' < custom-dictionary.txt | wc -l ) - 1 )); tmpfile="$(mktemp)"; echo "personal_ws-1.1 en $len utf-8" > …
```

EWS subtype updated

---

build/assets/custom-dictionary.txt
content/03.methods.md

Added description of neurocytoma subtype criteria.
https://github.com/AlexsLemonade/OpenPBTA-manuscript/issues/136
I do not have any references for the subtypes - assuming it was covered by WHO 2016 classification criteria. Please see whether that is fine. 
No.
Yes.
```
(( len = $(awk …
```

Neurocytoma Subtype update

---

content/03.methods.md

This is just for modifying some HGG nomenclatures to be consistent with the rest of the subtyping section.
https://github.com/AlexsLemonade/OpenPBTA-manuscript/issues/136
Please check to see whether the changes make sense. 
No.
Yes.
```
(( len = $(awk '!a[$0]++' < custom-dictionary.txt | …
```

HGG section nomenclature modification

---

content/metadata.yaml

Add author info for myself, and fix a typo I noticed in Laura Scolaro's affiliation ("Children's Hospital of Philadelphia" was duplicated)
Closes #144 
```
(( len = $(awk '!a[$0]++' < custom-dictionary.txt | wc -l ) - 1 )); tmpfile="$(mktemp)"; echo "personal_ws-1.1 en $len utf-8" > …
```

Add Laura Egolf as author (#144)

---

build/assets/custom-dictionary.txt
content/03.results.md
content/06.methods.md

Add methods for chromothripsis analysis with ShatterSeek.
#75
N/A
No
Yes
```
(( len = $(awk '!a[$0]++' < custom-dictionary.txt | wc -l ) - 1 )); tmpfile="$(mktemp)"; echo "personal_ws-1.1 en $len utf-8" > $tmpfile; tail -n +2 custom-dictionary.txt | awk '!a[$0]++' >> $tmpfile; mv $tmpfile …
```

Add chromothripsis methods

---

build/environment.yml

Manubot is failing https://github.com/AlexsLemonade/OpenPBTA-manuscript/pull/180#issuecomment-1064174543. Followed one of the solutions mentioned in https://github.com/manubot/manubot/issues/329

Pin markupsafe version

---

build/assets/custom-dictionary.txt
content/metadata.yaml

- add Run Jin, Shannon Robbins as authors
- update Krutika's email
#140 
#168 
NA
NA
yes
```
(( len = $(awk '!a[$0]++' < custom-dictionary.txt | wc -l ) - 1 )); tmpfile="$(mktemp)"; echo "personal_ws-1.1 en $len utf-8" > $tmpfile; tail -n +2 custom-dictionary.txt | awk '!a[$0]++' >> …
```

add Run Jin, Shannon Robbins, update Krutika's email

---

content/00.front-matter.md
content/metadata.yaml

Stephanie now works at CCDL and author credentials need to be updated accordingly.
#179 
I updated email and affiliation, but I'm not sure how to add a superscript in this format to indicate _current_ affiliation.
Superscript!
yes
```
(( …
```

Update spielman email and affil

---

content/06.methods.md

Add dois for:
Add table links for:
#175 
> Downstream data analyses: https://github.com/AlexsLemonade/OpenPBTA-analysis/
Manuscript code: https://github.com/AlexsLemonade/OpenPBTA-manuscript
These two will likely be added at the very end, once releases are made, not in this PR
no
```
(( …
```

WIP: add dois/key resource table updates

---

build/assets/custom-dictionary.txt
content/06.methods.md

to table in methods:
- remove broad composition
- add harmonized diagnosis
- add cancer group
- updated CNS region/put in alpha order
- update text
#129 
I see I initially had a table in here as S1 for pbta-histology file definitions and S2 for CNS region definitions (these are more of READMEs). However, we nowo have an official [Table S1](https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/tables/results/TableS1-histologies.xlsx), which has the content of the histologies file. So, Maybe we should add these S1 and S2 here as additional tabs in Table S1? These would have to be manually added. Should I keep these in for now and someone add them upon submission? I will add an HTML comment tag on this.
see above
soon
Unless …

Update diagnosis info in methods

---

content/06.methods.md

We now use `quanTIseq` and `xCell` (no longer `CIBERSORT`) for immune deconvolution. The methods section is updated to reflect the current methods.
#208 
NA
Are we definitely keeping xCell around?
Yes
```
(( len = $(awk '!a[$0]++' < …
```

Add quanTIseq to methods

---

build/assets/custom-dictionary.txt
content/05.administrative.md

Stephanie (SJS) also has a COI now!
```
(( len = $(awk '!a[$0]++' < custom-dictionary.txt | wc -l ) - 1 )); tmpfile="$(mktemp)"; echo "personal_ws-1.1 en $len utf-8" > $tmpfile; tail -n +2 custom-dictionary.txt | awk '!a[$0]++' >> $tmpfile; mv $tmpfile custom-dictionary.txt
```

Add SJS to declaration of interest

---

content/06.methods.md

removed MENDQC from QC section of methods
#231 
NA
no
yes
```
(( len = $(awk '!a[$0]++' < custom-dictionary.txt | wc -l ) - 1 )); tmpfile="$(mktemp)"; echo "personal_ws-1.1 en $len utf-8" > $tmpfile; tail -n +2 custom-dictionary.txt | awk '!a[$0]++' >> $tmpfile; mv $tmpfile …
```

remove mendQC

---

content/06.methods.md

from KF to OpenPBTA workflows repo
Update RNA-Seq and somatic workflows links to ensure proper versioning
#224 
Also noticed the somatic link needed updating. I generalized this to the CWL folder since there are so many workflows - ok?
yes
```
(( len = $(awk '!a[$0]++' < …
```

fix links to workflows used

---

content/metadata.yaml

Steven Foltz is added an an author with contribution of "Validation."

Add Steven Foltz as author

---

content/metadata.yaml

Closes #228.
This PR adds Yang Yang (@yangyangclover) as an author.

Yang Yang added as author

---

content/metadata.yaml

add Peter as author
#248 
no
yes
```
(( len = $(awk '!a[$0]++' < custom-dictionary.txt | wc -l ) - 1 )); tmpfile="$(mktemp)"; echo "personal_ws-1.1 en $len utf-8" > $tmpfile; tail -n +2 custom-dictionary.txt | awk '!a[$0]++' >> $tmpfile; …
```

add peter madsen as author

---

content/metadata.yaml

Add funding information for Steven Foltz
NA
Whitespace?
Nope
Yes
```
(( len = $(awk '!a[$0]++' < custom-dictionary.txt | wc -l ) - 1 )); tmpfile="$(mktemp)"; echo "personal_ws-1.1 en $len utf-8" > $tmpfile; tail -n +2 custom-dictionary.txt | awk '!a[$0]++' >> $tmpfile; mv $tmpfile …
```

Add Steven Foltz funding information

---

content/05.administrative.md

Add my funding info to acknowledgments section
NA
How to represent my ALSF CCDL post-doc grant
Nope
Yes thank you!
```
(( len = $(awk '!a[$0]++' < custom-dictionary.txt | wc -l ) - 1 )); tmpfile="$(mktemp)"; echo "personal_ws-1.1 en $len …
```

Add SF Acknowledgments

---

content/05.administrative.md

This PR adds Stephanie's funding acknowledgement. I had a Catalyst Grant for PBTA January 2020 - July 2021 (it was extended by 6 months b/c COVID).
Phrasing given that it's a _separate_ catalyst grant from the one already there?
No
Yes
```
(( len = $(awk '!a[$0]++' < custom-dictionary.txt …
```

Add Stephanie's grant to acknowledgements

---

content/metadata.yaml

Adding my current affiliation and email to the `content/metadata.yaml` file. 
related to #315
I followed the formatting of the other folks who put their updated affiliations in addition to the affiliation they had when the work on this started. 
This looks like it re-rendered correctly. Just check that it is inline with the other affiliations. 
I think so but was gonna see what it looked like in the automatic preview. 
**None of these items are really applicable:** 
**I also don't believe this is applicable**
You do not need to change …

Update cansavvy's affiliations

---

content/05.administrative.md

Close #313 
#313 
Does this work?
Yes
```
(( len = $(awk '!a[$0]++' < custom-dictionary.txt | wc -l ) - 1 )); tmpfile="$(mktemp)"; echo "personal_ws-1.1 en $len utf-8" > $tmpfile; tail -n +2 custom-dictionary.txt | awk '!a[$0]++' >> …
```

see if this fixes contributions

---

content/metadata.yaml

Update
- emails for Laura E, Run J, Nick V
- middle initial for Angela V
Closes #315 
Closes #319 
Yes
```
(( len = $(awk '!a[$0]++' < custom-dictionary.txt | wc -l ) - 1 )); tmpfile="$(mktemp)"; echo "personal_ws-1.1 en $len utf-8" > $tmpfile; tail -n +2 custom-dictionary.txt | awk …
```

update CHOP affiliations

---

content/metadata.yaml

update shannon robins name and orcid

update shannon robins name and orcid

---

content/03.results.md
content/metadata.yaml

Comments:
>1. My affiliation: D3b stands for "Center for Data-Driven Discovery in Biomedicine", also need to double check if I am affiliated with Neurosurgery.
>2. Page 17 around sentence "two LFS patient tumors with low TP53 scores": So both tumor biospecimens are from a single patient? I would make that clear, or was it written somewhere else?
>3. Page 18 around sentence "While we did not find a known pathogenic variant in the germline of PT_VTM2STE3": I just saw a reported PMS2 variant in this participant’s germline data as attached, although with high minor allele frequency of 2% in the general population. I also attach HGMD records for this variant (it's messy but you should be able to read the PubMed IDs 19526325|10480359|11793469|22703879|22949387|22995991|24689082|24728327|25525159 …

Edits from Yiran G

---

content/01.summary.md
content/metadata.yaml

Closes #334 
Closes #332 
Also updated:
- make keywords consistent between keywords section in front matter and in the metadata.yaml file (although i am not sure if they need to be connected)
- move all author affil to one per line (some were split)
- update yinyang superscript for @sjspielman

Contributions update

---

content/03.results.md
content/06.methods.md

I made a few minor text edits to try to improve clarity. Feel free to ignore/revert back.
- Added link and full name for KFDRC in the Results (this is the first place KFDRC is mentioned in the paper) 
- Tweaked wording for CNV/SV breakpoint density in Results (see also comment below)
- Tweaked wording in chromothripsis methods to fix a run-on sentence
I have a couple additional comments:
- **Minor comment**: Make sure to check the references in the introduction section that discusses FDA approvals. 
--- _EDIT: Nevermind, I see this has already been mentioned in an issue._
- **Somewhat-less-minor comment**: We should probably include methods for the `chromosomal-instability` module since the breakpoint results are included in the paper. SV breakpoint density is pretty straightforward since …

Edits from Laura Egolf

---

build/assets/custom-dictionary.txt
content/05.administrative.md

add AJW declaration of interest

add AJW declaration of interest

---

content/metadata.yaml

Adding self to author list
#393 
Is my formatting correct? Did I add all necessary fields?
Yes
```
(( len = $(awk '!a[$0]++' < custom-dictionary.txt | wc -l ) - 1 )); tmpfile="$(mktemp)"; echo "personal_ws-1.1 en $len utf-8" > $tmpfile; tail -n +2 custom-dictionary.txt | awk '!a[$0]++' >> …
```

Add gwaybio to author list

---

content/metadata.yaml

Adding:
- Chris Blackden (Resources for DevOps/computational resources and support)
- Eric Wafula (Formal Analysis - for updates to EPN module pre-submission and Software - for testing and reviewing code for the nucleic acid extraction code)
- Noel Coleman (Data curation - for curating all nucleic acid extraction information)
#393 
No
Do the above roles seem correct/reasonable?
I am asking Chris whether he has an ORCID, so will circle back.
You do …

Add Chris B, Eric W, Noel C as authors

---

content/metadata.yaml

Closes #387 
This PR adds three missing items to my contributions - 
- `Writing - Original draft`
- `Investigation`
- `Software`

Update Spielman contributions

---

content/06.methods.md

Closes #398 
This PR updates the UMAP methods to state that we use all samples but only genes at >= 100 count.
Any phrasing feedback?

Add UMAP samples caveat

---

content/03.results.md

Closes #365
This PR adds a couple new citations to round out this reviewer comment. Feedback on phrasing (especially the last sentence I modified -  is it too wordy?) is welcome!

Add new citations for recapitulated results

---

content/03.results.md

I lightly borked #411 by merging without suggestions being properly accepted! Those suggestions are implemented here. Sorry for confusion, @jharenza !

Recapitulated cleanups

---

content/03.results.md
content/06.methods.md

Add sentence about stranded sample use in Results section.
Fix subscript issue in methods
Add that PNOC samples are polyA
Closes #423 
yes
```
(( len = $(awk '!a[$0]++' < custom-dictionary.txt | wc -l ) - 1 )); tmpfile="$(mktemp)"; echo …
```

add stranded expansion, fix subscript issue

---

build/assets/custom-dictionary.txt
content/06.methods.md

This PR adds tumor purity assessment to the methods section
#427 method only
Just adding method. Saw you assigned yourself @sjspielman after I started the method -sorry! We can add the figure in a separate PR
yes
```
(( len = $(awk '!a[$0]++' < custom-dictionary.txt | wc -l ) - 1 )); …
```

add tumor purity assessment to methods

---

content/00.front-matter.md
content/metadata.yaml

1. All full affiliations
2. Add updates given by authors in [this](https://docs.google.com/spreadsheets/d/1rtCDjNECWDJmsmAAN4AdCdAIUicwRa4-UmSoZLCUD_Q/edit#gid=1182772523) google sheet.

Update author details

---

content/06.administrative.md

Based on our survey results from authors and the CBTN, as well as having no objections to inclusion of the DI statement, I am adding the responses here.
Closes #472 #457

add inclusion and diversity statement
